StudyDirectionDbWebApp/Controllers/ChairsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using StudyDirectionDbWebApp.Models;
using StudyDirectionDbWebApp.Utility;

namespace StudyDirectionDbWebApp.Controllers
{
    public class ChairsController : Controller
    {
        private StudyDirectionDbEntities1 db = new StudyDirectionDbEntities1();

        protected override void Initialize(RequestContext context)
        {
            base.Initialize(context);

            db.Database.Log = DatabaseLogger.Log;

            ViewBag.Controller = "Кафедры";
        }

        // GET: Chairs
        public async Task<ActionResult> Index()
        {
            var chairs = db.Chairs.Include(c => c.Faculty);
            return View(await chairs.ToListAsync());
        }

        // GET: Chairs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chair chair = await db.Chairs.FirstAsync(x=>x.ChairId == id);
            if (chair == null)
            {
                return HttpNotFound();
            }
            return View(chair);
        }

        // GET: Chairs/Create
        public ActionResult Create()
        {
            ViewBag.FacultyId = new SelectList(db.Faculties, "FacultyId", "Name");
            return View();
        }

        // POST: Chairs/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "FacultyId,ChairId,ChairName")] Chair chair)
        {
            if (ModelState.IsValid)
            {
                db.Chairs.Add(chair);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.FacultyId = new SelectList(db.Faculties, "FacultyId", "Name", chair.FacultyId);
            return View(chair);
        }

        // GET: Chairs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chair chair = await db.Chairs.FirstAsync(x => x.ChairId == id);
            if (chair == null)
            {
                return HttpNotFound();
            }
            ViewBag.FacultyId = new SelectList(db.Faculties, "FacultyId", "Name", chair.FacultyId);
            return View(chair);
        }

        // POST: Chairs/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "FacultyId,ChairId,ChairName")] Chair chair)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chair).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FacultyId = new SelectList(db.Faculties, "FacultyId", "Name", chair.FacultyId);
            return View(chair);
        }

        // GET: Chairs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chair chair = await db.Chairs.FirstAsync(x => x.ChairId == id);
            if (chair == null)
            {
                return HttpNotFound();
            }
            return View(chair);
        }

        // POST: Chairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Chair chair = await db.Chairs.FirstAsync(x => x.ChairId == id);
            db.Chairs.Remove(chair);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudyDirectionDbWebApp/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using StudyDirectionDbWebApp.Models;
using StudyDirectionDbWebApp.Utility;

namespace StudyDirectionDbWebApp.Controllers
{
    public class GroupsController : Controller
    {
        private StudyDirectionDbEntities1 db = new StudyDirectionDbEntities1();

        protected override void Initialize(RequestContext context)
        {
            base.Initialize(context);

            db.Database.Log = DatabaseLogger.Log;

            ViewBag.Controller = "Группы";
        }

        // GET: Groups
        public async Task<ActionResult> Index()
        {
            var groups = db.Groups.Include(g => g.StudyDirection).Include(g => g.StudyForm);
            return View(await groups.ToListAsync());
        }

        // GET: Groups/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FirstAsync(x => x.GroupId == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            ViewBag.DirectionId = new SelectList(db.StudyDirections, "DirectionId", "StudyDirectionName");
            ViewBag.Form = new SelectList(db.StudyForms, "Form", "Form");
            return View();
        }

        // POST: Groups/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "FacultyId,ChairId,SpecialityId,DirectionId,GroupId,Form")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.DirectionId = new SelectList(db.StudyDirections, "DirectionId", "StudyDirectionName", group.DirectionId);
            ViewBag.Form = new SelectList(db.StudyForms, "Form", "Form", group.Form);
            return View(group);
        }

        // GET: Groups/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FirstAsync(x => x.GroupId == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.DirectionId = new SelectList(db.StudyDirections, "DirectionId", "StudyDirectionName", group.DirectionId);
            ViewBag.Form = new SelectList(db.StudyForms, "Form", "Form", group.Form);
            return View(group);
        }

        // POST: Groups/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "FacultyId,ChairId,SpecialityId,DirectionId,GroupId,Form")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.DirectionId = new SelectList(db.StudyDirections, "DirectionId", "StudyDirectionName", group.DirectionId);
            ViewBag.Form = new SelectList(db.StudyForms, "Form", "Form", group.Form);
            return View(group);
        }

        // GET: Groups/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FirstAsync(x => x.GroupId == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Group group = await db.Groups.FirstAsync(x => x.GroupId == id);
            db.Groups.Remove(group);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudyDirectionDbWebApp/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudyDirectionDbWebApp.Controllers
{
    public class HelpController : Controller
    {
        // GET: Help
        public ActionResult Purpose()
        {
            return View();
        }

        // GET: Help
        public ActionResult RuntimeConditions()
        {
            return View();
        }
        // GET: Help
        public ActionResult Running()
        {
            return View();
        }
        // GET: Help
        public ActionResult ExecutionOrder()
        {
            return View();
        }
        // GET: Help
        public ActionResult FunctionsDescription()
        {
            return View();
        }
        // GET: Help
        public ActionResult OperatorMessages()
        {
            return View();
        }
    }
}

StudyDirectionDbWebApp/Controllers/LogController.cs
using System.Net;
using System.Web.Mvc;

namespace StudyDirectionDbWebApp.Controllers
{
    public class LogController : Controller
    {
        // GET: Log
        public ActionResult Index(int? page, int? id)
        {
            if (page == null)
                page = 1;

            ViewBag.Page = page;

            if (id == null)
            {
                return View(page);
            }

            return Redirect("#"+id);
        }
    }
}

StudyDirectionDbWebApp/Views/Shared/LastQueries.cshtml
@using StudyDirectionDbWebApp.Models
@{
    const int defaultTakenNumberOfMessages = 15;
    var db = new StudyDirectionDbEntities1();
    int counter = 0;
    var lastIdRead = LoggerInfoAdapter.Get(Server.MapPath("~/App_Data/loggerInfo.json")).LastId;
    var lastIdInBase = db.Logs.OrderByDescending(x => x.LogId).First().LogId;
    var amountOfUnreadMessages = lastIdInBase - lastIdRead;
    var takenNumberOfMessages = amountOfUnreadMessages > defaultTakenNumberOfMessages ? defaultTakenNumberOfMessages : amountOfUnreadMessages;
}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell"></i>
        <span class="badge">@amountOfUnreadMessages</span>
    </a>
    <ul class="dropdown-menu">
        @foreach (var log in db.Logs.OrderByDescending(x => x.LogId).Take(takenNumberOfMessages))
        {
            counter++;
            <li>
                <a href="@Url.Action("Index", "Log", new {id = counter})">
                    <i class="fa fa-envelope"></i>
                    @if (log.Message.Length < 95)
                    {
                        <span>@log.Message</span>
                    }
                    else
                    {
                        <span>@log.Message.Substring(0, 95)</span>
                    }

                </a>
            </li>
        }
    </ul>
</li>

StudyDirectionDbWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>

    <title>@ViewBag.Title – Каталог специальностей</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>

<header class="navbar">
    <div class="container-fluid expanded-panel">
        <div class="row">
            <div id="logo" class="col-xs-12 col-sm-2">
                <a href="@Url.Action("Index","Home")">Специальности</a>
            </div>
            <div id="top-panel" class="col-xs-12 col-sm-10">
                <div class="row">
                    <div class="col-xs-8 col-sm-4">
                        <a href="#" class="show-sidebar">
                            <i class="fa fa-bars"></i>
                        </a>
                        <div id="search">
                            <input type="text" placeholder="search"/>
                            <i class="fa fa-search"></i>
                        </div>
                    </div>
                    <div class="col-xs-4 col-sm-8 top-panel-right">
                        <ul class="nav navbar-nav pull-right panel-menu">
                            <li class="hidden-xs">
                                <a href="@Url.Action("Index", "Home")" class="modal-link">

                                </a>
                            </li>
                            <li class="hidden-xs">
                                <a href="@Url.Action("Index", "Calendar")">
                                    <i class="fa fa-calendar"></i>
                                    <span class="badge">0</span>
                                </a>
                            </li>
                            

                            @Html.Partial("LastQueries")
                            @Html.Partial("_LoginPartial")
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
    <!--Start Container-->
    <div id="main" class="container-fluid">
        <div class="row">
            <div id="sidebar-left" class="col-xs-2 col-sm-2">
                <ul class="nav main-menu">
                    <li>
                        <a href="@Url.Action("Index","Home")">
                            <i class="fa fa-dashboard"></i>
                            <span class="hidden-xs">Основная панель</span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle">
                            <i class="fa fa-table"></i>
                            <span class="hidden-xs">Таблицы</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Faculties")">Факультеты</a></li>
                            <li><a href="@Url.Action("Index", "Chairs")">Кафедры</a></li>
                            <li><a href="@Url.Action("Index", "Specialities")">Специальности</a></li>
                            <li><a href="@Url.Action("Index", "StudyDirections")">Направления подготовки</a></li>
                            <li><a href="@Url.Action("Index", "StudyForms")">Формы подготовки</a></li>
                            <li><a href="@Url.Action("Index", "Groups")">Группы</a></li>
                            <li><a href="@Url.Action("Index", "Students")">Студенты</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle">
                            <i class="fa fa-question"></i>
                            <span class="hidden-xs">Справка</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Purpose", "Help")">Назначение программы</a></li>
                            <li><a href="@Url.Action("RuntimeConditions", "Help")">Условия выполнения программы</a></li>
                            <li><a href="@Url.Action("Running", "Help")">Выполнение программы</a></li>
                            <li><a href="@Url.Action("ExecutionOrder", "Help")">Порядок запуска, выполнения и завершения программы</a></li>
                            <li><a href="@Url.Action("FunctionsDescription", "Help")">Описание функций</a></li>
                            <li><a href="@Url.Action("OperatorMessages", "Help")">Сообщения оператору</a></li>
                        </ul>
                    </li>
                    

                </ul>
            </div>
            <!--Start Content-->
            <div id="content" class="col-xs-12 col-sm-10">
                <!--Start Breadcrumb-->
                <div class="row">
                    <div id="breadcrumb" class="col-xs-12">
                        <ol class="breadcrumb">
                            <li>@Html.ActionLink("Основная панель", "Index", "Home")</li>
                            @if (ViewBag.Controller != null && ViewBag.Title != null)
                            {
                                <li>
                                    <a href="@Url.Action("Index",ViewBag.Controller)">@ViewBag.Controller</a>
                                </li>
                                <li>
                                    <a href="@Url.Action(ViewBag.Title, ViewBag.Controller)">@ViewBag.Title</a>
                                </li>
                            }
                        </ol>
                    </div>
                </div>
                <!--End Breadcrumb-->
                @RenderBody()
            </div>
            <!--End Content-->
        </div>
    </div>
    <!--End Container-->



@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/devoops")
@Scripts.Render("~/bundles/bootstrap")


@RenderSection("scripts", required: false)
</body>
</html>